"""baseline schema

Revision ID: 5cc92be0ef43
Revises: 
Create Date: 2026-07-27 19:12:14.924235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cc92be0ef43'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_blueprints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('segment', sa.String(length=50), nullable=False),
    sa.Column('adr', sa.Float(), nullable=False),
    sa.Column('rooms', sa.Integer(), nullable=False),
    sa.Column('developer_goal', sa.Text(), nullable=False),
    sa.Column('source_trend_id', sa.String(length=36), nullable=True),
    sa.Column('profile_data_json', sa.JSON(), nullable=True),
    sa.Column('brand_name_primary', sa.String(length=200), nullable=False),
    sa.Column('brand_name_alt_1', sa.String(length=200), nullable=True),
    sa.Column('brand_name_alt_2', sa.String(length=200), nullable=True),
    sa.Column('one_liner', sa.String(length=500), nullable=False),
    sa.Column('thesis', sa.Text(), nullable=False),
    sa.Column('pillars', sa.JSON(), nullable=False),
    sa.Column('positioning_statement', sa.Text(), nullable=False),
    sa.Column('unmet_desires_solved', sa.JSON(), nullable=False),
    sa.Column('guest_personas', sa.JSON(), nullable=False),
    sa.Column('signature_experiences', sa.JSON(), nullable=False),
    sa.Column('guest_journey', sa.JSON(), nullable=True),
    sa.Column('design_direction', sa.Text(), nullable=False),
    sa.Column('fnb_concepts', sa.JSON(), nullable=False),
    sa.Column('revenue_logic', sa.Text(), nullable=False),
    sa.Column('investor_summary', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brand_blueprints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brand_blueprints_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_brand_blueprints_location'), ['location'], unique=False)
        batch_op.create_index(batch_op.f('ix_brand_blueprints_segment'), ['segment'], unique=False)
        batch_op.create_index(batch_op.f('ix_brand_blueprints_user_id'), ['user_id'], unique=False)

    op.create_table('demand_metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('metric', sa.String(length=100), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'city', 'metric', 'date', name='uq_demand_metric_point')
    )
    with op.batch_alter_table('demand_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_demand_metrics_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_demand_metrics_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_demand_metrics_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_demand_metrics_metric'), ['metric'], unique=False)
        batch_op.create_index(batch_op.f('ix_demand_metrics_source'), ['source'], unique=False)

    op.create_table('hotelier_moves',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('why_it_matters', sa.Text(), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('company_type', sa.String(length=50), nullable=True),
    sa.Column('move_type', sa.String(length=30), nullable=False),
    sa.Column('market', sa.String(length=100), nullable=True),
    sa.Column('investment_amount', sa.String(length=50), nullable=True),
    sa.Column('strategic_implications', sa.JSON(), nullable=True),
    sa.Column('competitive_impact', sa.Text(), nullable=True),
    sa.Column('related_trends', sa.JSON(), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(), nullable=False),
    sa.Column('source_content_id', sa.String(length=36), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hotelier_moves', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hotelier_moves_company'), ['company'], unique=False)
        batch_op.create_index(batch_op.f('ix_hotelier_moves_extracted_at'), ['extracted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_hotelier_moves_market'), ['market'], unique=False)
        batch_op.create_index(batch_op.f('ix_hotelier_moves_move_type'), ['move_type'], unique=False)

    op.create_table('ledger_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('prediction_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=True),
    sa.Column('metric', sa.String(length=100), nullable=True),
    sa.Column('actual_value', sa.Float(), nullable=True),
    sa.Column('outcome_json', sa.JSON(), nullable=True),
    sa.Column('evidence_refs', sa.JSON(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ledger_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ledger_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_events_prediction_id'), ['prediction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_events_recorded_at'), ['recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_events_stage'), ['stage'], unique=False)

    op.create_table('prediction_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('signal_date', sa.DateTime(), nullable=False),
    sa.Column('signal_source', sa.String(length=200), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=False),
    sa.Column('product_implication', sa.Text(), nullable=False),
    sa.Column('location_thesis', sa.Text(), nullable=True),
    sa.Column('forecasts', sa.JSON(), nullable=True),
    sa.Column('uncertainty_notes', sa.Text(), nullable=True),
    sa.Column('methodology_version', sa.String(length=50), nullable=False),
    sa.Column('project', sa.String(length=200), nullable=True),
    sa.Column('source_trend_ids', sa.JSON(), nullable=True),
    sa.Column('source_content_ids', sa.JSON(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_summary', sa.Text(), nullable=True),
    sa.Column('highest_evidence_stage', sa.String(length=30), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prediction_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prediction_records_highest_evidence_stage'), ['highest_evidence_stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_prediction_records_project'), ['project'], unique=False)
        batch_op.create_index(batch_op.f('ix_prediction_records_recorded_at'), ['recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_prediction_records_signal_date'), ['signal_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_prediction_records_status'), ['status'], unique=False)

    op.create_table('processing_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('items_processed', sa.Integer(), nullable=False),
    sa.Column('items_failed', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property_features',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.Column('property_type', sa.String(length=30), nullable=False),
    sa.Column('brand_positioning', sa.Text(), nullable=True),
    sa.Column('tagline', sa.String(length=500), nullable=True),
    sa.Column('tone', sa.String(length=200), nullable=True),
    sa.Column('themes', sa.JSON(), nullable=True),
    sa.Column('amenities', sa.JSON(), nullable=True),
    sa.Column('room_types', sa.JSON(), nullable=True),
    sa.Column('dining_options', sa.JSON(), nullable=True),
    sa.Column('experiences', sa.JSON(), nullable=True),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('price_segment', sa.String(length=30), nullable=False),
    sa.Column('price_indicators', sa.JSON(), nullable=True),
    sa.Column('demand_fit_score', sa.Float(), nullable=True),
    sa.Column('experience_gaps', sa.JSON(), nullable=True),
    sa.Column('opportunity_lanes', sa.JSON(), nullable=True),
    sa.Column('competitive_advantages', sa.JSON(), nullable=True),
    sa.Column('positioning_misalignment_flags', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('matching_trend_ids', sa.JSON(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.Column('source_content_id', sa.String(length=36), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('property_features', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_property_features_property_type'), ['property_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_property_features_region'), ['region'], unique=False)
        batch_op.create_index(batch_op.f('ix_property_features_url'), ['url'], unique=True)

    op.create_table('raw_content',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('embedding_id', sa.String(length=36), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    with op.batch_alter_table('raw_content', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_content_is_processed'), ['is_processed'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_content_scraped_at'), ['scraped_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_content_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_content_source_type'), ['source_type'], unique=False)

    op.create_table('saved_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('snapshot_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'item_type', 'item_id', name='uq_saved_item_per_user')
    )
    with op.batch_alter_table('saved_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_items_user_id'), ['user_id'], unique=False)

    op.create_table('trend_signals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('why_it_matters', sa.Text(), nullable=False),
    sa.Column('strength_score', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('engagement_score', sa.Float(), nullable=False),
    sa.Column('sentiment_delta', sa.Float(), nullable=False),
    sa.Column('white_space_score', sa.Float(), nullable=False),
    sa.Column('demand_signals', sa.Integer(), nullable=False),
    sa.Column('supply_signals', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('audience_segment', sa.String(length=50), nullable=False),
    sa.Column('topics', sa.JSON(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('time_window_days', sa.Integer(), nullable=False),
    sa.Column('source_content_ids', sa.JSON(), nullable=True),
    sa.Column('sample_quotes', sa.JSON(), nullable=True),
    sa.Column('cluster_id', sa.String(length=36), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trend_signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trend_signals_last_updated'), ['last_updated'], unique=False)
        batch_op.create_index(batch_op.f('ix_trend_signals_region'), ['region'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('trend_signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trend_signals_region'))
        batch_op.drop_index(batch_op.f('ix_trend_signals_last_updated'))

    op.drop_table('trend_signals')
    with op.batch_alter_table('saved_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_items_user_id'))

    op.drop_table('saved_items')
    with op.batch_alter_table('raw_content', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_content_source_type'))
        batch_op.drop_index(batch_op.f('ix_raw_content_source'))
        batch_op.drop_index(batch_op.f('ix_raw_content_scraped_at'))
        batch_op.drop_index(batch_op.f('ix_raw_content_is_processed'))

    op.drop_table('raw_content')
    with op.batch_alter_table('property_features', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_property_features_url'))
        batch_op.drop_index(batch_op.f('ix_property_features_region'))
        batch_op.drop_index(batch_op.f('ix_property_features_property_type'))

    op.drop_table('property_features')
    op.drop_table('processing_jobs')
    with op.batch_alter_table('prediction_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prediction_records_status'))
        batch_op.drop_index(batch_op.f('ix_prediction_records_signal_date'))
        batch_op.drop_index(batch_op.f('ix_prediction_records_recorded_at'))
        batch_op.drop_index(batch_op.f('ix_prediction_records_project'))
        batch_op.drop_index(batch_op.f('ix_prediction_records_highest_evidence_stage'))

    op.drop_table('prediction_records')
    with op.batch_alter_table('ledger_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledger_events_stage'))
        batch_op.drop_index(batch_op.f('ix_ledger_events_recorded_at'))
        batch_op.drop_index(batch_op.f('ix_ledger_events_prediction_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_events_event_type'))

    op.drop_table('ledger_events')
    with op.batch_alter_table('hotelier_moves', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hotelier_moves_move_type'))
        batch_op.drop_index(batch_op.f('ix_hotelier_moves_market'))
        batch_op.drop_index(batch_op.f('ix_hotelier_moves_extracted_at'))
        batch_op.drop_index(batch_op.f('ix_hotelier_moves_company'))

    op.drop_table('hotelier_moves')
    with op.batch_alter_table('demand_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_demand_metrics_source'))
        batch_op.drop_index(batch_op.f('ix_demand_metrics_metric'))
        batch_op.drop_index(batch_op.f('ix_demand_metrics_date'))
        batch_op.drop_index(batch_op.f('ix_demand_metrics_country'))
        batch_op.drop_index(batch_op.f('ix_demand_metrics_city'))

    op.drop_table('demand_metrics')
    with op.batch_alter_table('brand_blueprints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brand_blueprints_user_id'))
        batch_op.drop_index(batch_op.f('ix_brand_blueprints_segment'))
        batch_op.drop_index(batch_op.f('ix_brand_blueprints_location'))
        batch_op.drop_index(batch_op.f('ix_brand_blueprints_created_at'))

    op.drop_table('brand_blueprints')
    # ### end Alembic commands ###
